[build-system]
  build-backend = "uv_build"
  requires = ["uv_build"]

[project]
  name = "dycw-action-template"
  requires-python = ">= 3.13"

[dependency-groups]
  dev = ["dycw-utilities[test]", "rich"]
