[build-system]
  build-backend = "uv_build"
  requires = ["uv_build"]

[project]
  description = "Template for Python actions"
  name = "dycw-action-template"
  readme = "README.md"
  requires-python = ">= 3.13"
  version = "0.1.0"

[dependency-groups]
  dev = ["dycw-utilities[test]", "rich"]
