name: pull-request
on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: 37 13 * * *
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name == 'pull_request'
        name: Run 'pre-commit' hooks
        uses: dycw/action-run-hooks@latest
        with:
          repos: |-
            dycw/actions
            pre-commit/pre-commit-hooks
