jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Tag latest commit
        uses: dycw/action-tag@latest
        with:
          latest: true
          major: true
          major-minor: true
          token: ${{ secrets.GITHUB_TOKEN }}
name: push
"on":
  push:
    branches:
      - master
