jobs:
  publish:
    environment:
      name: pypi
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Build Python package and upload distribution
        uses: dycw/action-uv-publish@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          trusted-publishing: true
      - name: Build and publish Python packages
        uses: dycw/action-uv-publish@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          trusted-publishing: true
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Tag latest commit
        uses: dycw/action-tag-commit@latest
        with:
          latest: true
          major: true
          major-minor: true
          token: ${{ secrets.GITHUB_TOKEN }}
name: push
"on":
  push:
    branches:
      - master
